/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app;

import javax.swing.JOptionPane;

/**
 *
 * @author olive
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        ImagenIcon = new javax.swing.JLabel();
        label_title = new javax.swing.JLabel();
        label_imagen = new javax.swing.JLabel();
        label_iniciar_seccion = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        labelUsuario = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        labelContrasena = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        fieldContasena = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/pngfind.com-enterprise-png-6659827 (1).png"))); // NOI18N
        backgroundPanel.add(ImagenIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        label_title.setBackground(new java.awt.Color(255, 255, 255));
        label_title.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        label_title.setForeground(new java.awt.Color(255, 255, 255));
        label_title.setText("Logic Master");
        backgroundPanel.add(label_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, -1));

        label_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/fondo.png"))); // NOI18N
        label_imagen.setText("jLabel1");
        backgroundPanel.add(label_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 360, 440));

        label_iniciar_seccion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_iniciar_seccion.setText("Iniciar Seccion");
        backgroundPanel.add(label_iniciar_seccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        tf_usuario.setBorder(null);
        tf_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usuarioActionPerformed(evt);
            }
        });
        backgroundPanel.add(tf_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 370, 30));

        labelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelUsuario.setText("Usuario");
        backgroundPanel.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        backgroundPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 370, 30));

        labelContrasena.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelContrasena.setText("Contraseña");
        backgroundPanel.add(labelContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        backgroundPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 370, 30));

        fieldContasena.setBorder(null);
        fieldContasena.setCaretColor(new java.awt.Color(204, 204, 204));
        backgroundPanel.add(fieldContasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 370, -1));

        jButton1.setBackground(new java.awt.Color(248, 189, 81));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Entrar");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setDefaultCapable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        backgroundPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 100, 30));

        jButton2.setBackground(new java.awt.Color(40, 42, 43));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        backgroundPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usuarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                        
        String nombreUsuario = tf_usuario.getText();
        String contrasena = new String(fieldContasena.getPassword());
        menu pMenu = new menu();
        

        if ((nombreUsuario.equals("administrador") && contrasena.equals("administrator123456")) ||
            (nombreUsuario.equals("admin") && contrasena.equals("admin1234567")) ||
            (nombreUsuario.equals("rrhh") && contrasena.equals("rrhh12345678"))) {
            JOptionPane.showMessageDialog(this, "¡Acceso concedido!");
            pMenu.setVisible(true);
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(this, "Nombre de usuario o contraseña incorrectos.", "Error de autenticación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenIcon;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPasswordField fieldContasena;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel label_imagen;
    private javax.swing.JLabel label_iniciar_seccion;
    private javax.swing.JLabel label_title;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
}
